### ISSUE TITLE
Isomorphic errors

### ISSUE THREAD

**Issue by corbifex** [thangngoc89/react-howler#8]
When you use react isomorphic it will give errors because howler use navigator which is not available in nodejs.

> ReferenceError: navigator is not defined
     at e (/node_modules/howler/howler.min.js:2:385)
     at /node_modules/howler/howler.min.js:2:800
     at Object.<anonymous> (/node_modules/howler/howler.min.js:2:19670)
      at Module._compile (module.js:434:26)
      at Object.Module._extensions..js (module.js:452:10)
      at Module.load (module.js:355:32)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (module.js:384:17)
      at Object.<anonymous> (/node_modules/react-howler/lib/ReactHowler.js:13:16)
      at Module._compile (module.js:434:26)
      at Object.Module._extensions..js (module.js:452:10)
      at Module.load (module.js:355:32)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (module.js:384:17)
      at Object.<anonymous> (/node_modules/react-howler/lib/index.js:3:18)
      at Module._compile (module.js:434:26)
      at Object.Module._extensions..js (module.js:452:10)
      at Module.load (module.js:355:32)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (module.js:384:17)

**Comment by thangngoc89** [comment]
Well.  Like you said,  howler relied on navigator.  Maybe before you require ReactHowler,  you should check if `window` object is available.  

```js
if (typeof window !== 'undefined') {
  // require howler here,  do stuff
}
```

**Comment by corbifex** [comment]
I can make a workaround no problem, but I thought maybe you can or want to build it in by the module by default.

**Comment by thangngoc89** [comment]
Do you have any idea how to do it ?  PRs are welcome

**Comment by corbifex** [comment]
I would say that your window solution can work inside initHowler() to prevent it from loading Howler on server side.

**Comment by thangngoc89** [comment]
Looks like a solution to me. Care to send a PR ?

This might be related https://github.com/goldfire/howler.js/issues/422

**Comment by corbifex** [comment]
I want to but the problem I get now is that when `import { Howl } from 'howler'` is fired the error appears. But doing the window check there is not allowed. So either it needs to be solved in the howler module of in the index, I don't think solving it in the index.js is a nice solution.

**Comment by thangngoc89** [comment]
:+1: so add new file to resolve howler,  if we are in node, return undefined

**Comment by thangngoc89** [comment]
Close by #9
